#!/bin/bash

while getopts "h" option
do
	echo "Помощь : "
	echo "Скрипт запускается и выводит на экран имена всех файлов из текущей директории, которые имеют расширение \".txt\". Далее для отображения содержимого интересующего вас файла введите число, соответствующее его номеру на экране. Для выхода нажмите клавишу q. После вывода на экран содержимого файла скрипт повторит работу."
	exit 0
done

while true
do
	echo ""
	echo "Список файлов в текущей директории, имеющих разрешение .txt :"
	filenames=( `find . -maxdepth 1 -type f -name "*.txt"` )
	if ((${#filenames[*]} == 0 ))
	then
		echo "В данной директории не содержится ни одного файла с разрешением .txt"
	fi
	for ((filenum=0; filenum<${#filenames[*]}; filenum++)); 
	do
		printf "$(( $filenum + 1 )) "
		echo ${filenames[$filenum]}
	done
	#имена файлов записаны в массив и выведены на экран
	
	echo "Выберите номер файла, содержимое которого вы хотите отобразить"
	read custom_file_num
	if [ "$custom_file_num" == "q" ]
	then
		exit 0
	fi
	case $custom_file_num in
    ''|*[!0-9]*) echo "Для ввода допустимы только целые числа больше ноля" ;;
		*)
			if (($custom_file_num > ${#filenames[*]})) || (($custom_file_num < 1))
			then
				echo "Введено некорректное значение номера файла."
			else
				echo "Первые 10 строк указанного файла :"
				head -n 10 ${filenames[$(( $custom_file_num - 1 ))]}
			fi
		;;
	esac
	#показаны первые 10 строчек нужного файла

done
